# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rodrigo Vargas - Web Developer
email: contato@rodrigovargas.me
description: > # this means to ignore newlines until "baseurl:"
  A blog about coding and development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rodrigovargas.me" # the base hostname & protocol for your site
github_username:  Rodrigo-Vargas

# Build settings
markdown: kramdown

collections:
  articles:
    output: true
    permalink: /articles/:categories/:path/
  works:
    output: true
    permalink: '/works/:path'
  certifications:
    output: true
    permalink: 'certifications/:path'
