title: Rodrigo Vargas Personal Website
email: rodrigovargas123@gmail.com
description:
  Blog pessoal de Rodrigo Vargas, um desenvolvedor fullstack que escreve sobre suas experiências usando várias tecnologias como C#, JavaScript, CSS entre outras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rodrigovargas.com.br"

enable_multi_language: true
lang: &LANG "pt"
permalink: /:title:output_ext

# Uncomment the section below to add items on your top navigation
header_items:
  -
    title: Portfolio
    href: /projects
  -
    title: Blog
    href: /blog

waterfall:
  author:
    name: Rodrigo Vargas
    description: Blog pessoal de Rodrigo Vargas, um desenvolvedor fullstack que escreve sobre suas experiências usando várias tecnologias como C#, JavaScript, CSS entre outras.

  social_links:
    github: Rodrigo-Vargas    
    linkedin: rodrigo-vargas-894a3637
    email: rodrigovargas123@gmail.com

  home:
    last_posts_items: 6

analytics:
  tracking_id: ""

google_tag_manager:
  tracking_id: "GTM-TW3SM7Q"

# Build settings
markdown: kramdown
theme: jekyll-waterfall

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

collections:
  posts:
    output: true
    permalink: /blog/:title:output_ext
  projects:
    output: true
  books:
    output: true
    permalink: /bookshelf/:path
  series:
    output: true
    permalink: /series/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      lang: *LANG
      layout: "default"

exclude:
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile
  - package-lock.json
  - package.json