# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rodrigo Vargas Personal Website
email: rodrigo@rodrigovargas.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Blog pessoal de Rodrigo Vargas, um desenvolvedor fullstack que escreve sobre suas experiências usando várias tecnologias como C#, JavaScript, CSS entre outras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rodrigovargas.com.br"
github_username:  rodrigo-vargas
author_name: Rodrigo Vargas
author_job: Full stack developer

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

collections:
  articles:
    output: true
    permalink: /blog/:path
  books:
    output: true
    permalink: /bookshelf/:path
  projects:
    output: true
    permalink: /projetos/:path
  series:
    output: true
    permalink: /series/:path
  skills:
    output: false
  education:
    output: false
  career:
    output: false
  posts:
    layout: article
    permalink: /:lang/:title:output_ext
defaults:
  -scope:
    path: "/blog"
    type: "articles"
  values:
    layout: article

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - src
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile
  - package-lock.json
  - package.json